
// Enum para la categoría de evento
export enum CategoryEvent {
  BIG_DATA = 'BIG_DATA',
  CIBERSEGURIDAD = 'CIBERSEGURIDAD',
  MACHINNELEARNING = 'MACHINNELEARNING',
  INTELIGENCIA_ARTIFICIAL = 'INTELIGENCIA_ARTIFICIAL',
  CLOUD = 'CLOUD',
  DEVOPS = 'DEVOPS',
  INNOVACION = 'INNOVACION',
  MACHINE_LEARNING = 'MACHINE_LEARNING',
  BLOCKCHAIN = 'BLOCKCHAIN',
}
